---
Resources:
  MyInstance1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0715c1897453cabd1
      InstanceType: t2.micro
      IamInstanceProfile: EC2-Role-S3-Access
  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0715c1897453cabd1
      InstanceType: t2.micro
      IamInstanceProfile: EC2-Role-S3-Access
  MyInstance3:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0715c1897453cabd1
      InstanceType: t2.micro
      IamInstanceProfile: EC2-Role-S3-Access